[[events]]

== what's up asciidoc!!!

Beans may produce and consume events. This facility allows beans to interact in a completely decoupled fashion, with no compile-time dependency between the interacting beans. Most importantly, it allows stateful beans in one architectural tier of the application to synchronize their internal state with state changes that occur in a different tier.

An event comprises:

* A Java object - the _event object_
* A set of instances of qualifier types - the _event qualifiers_



[[anchor-1]]
Paragraph or block 1.

anchor:anchor-2[]
Paragraph or block 2.

<<anchor-1>>,
<<anchor-1,First anchor>>,
xref:anchor-2[],
xref:anchor-2[Second anchor].

  

Paragraph or block 1.

Paragraph or block 2.

[anchor-1], First anchor, [anchor-2], Second anchor.

link:asciidoc[This document]
link:asciidoc.html[]
link:/index.html[This site root]

	

This document asciidoc.html This site root

http://google.com
http://google.com[Google Search]
mailto:root@localhost[email admin]

